modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"

[[mods]]
modId="${mod_id}"
logoFile="icon.png"
version="${mod_version}"
displayName="${mod_name}"

authors="Atoba Azul, Albatroz Feroz"

description='''
Adds content bridging Iron's Arms and Artifice
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="malum"
    type="required"
    versionRange="[1.8.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="irons_artifice"
    type="required"
    versionRange="[1.0.1,)"
    ordering="NONE"
    side="BOTH"